# Generated by Django 5.2.16 on 2026-07-14 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('ARCHIVE', 'ARCHIVE'), ('RESTORE', 'RESTORE'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('DOWNLOAD', 'DOWNLOAD'), ('EXPORT', 'EXPORT'), ('PERMISSION_CHANGE', 'PERMISSION_CHANGE'), ('ROLE_CHANGE', 'ROLE_CHANGE')], max_length=50, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de entidad')),
                ('record_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID del registro')),
                ('prev_data', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('post_data', models.JSONField(blank=True, null=True, verbose_name='Datos posteriores')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Método HTTP')),
                ('result', models.CharField(default='SUCCESS', max_length=50, verbose_name='Resultado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
