# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('ARCHIVE', 'Archivar'), ('RESTORE', 'Restaurar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Inicio fallido'), ('DOWNLOAD', 'Descargar'), ('EXPORT', 'Exportar'), ('PRINT', 'Imprimir'), ('GENERATE', 'Generar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('CANCEL', 'Cancelar'), ('VOID', 'Anular'), ('REVERSE', 'Reversar'), ('STATUS_CHANGE', 'Cambiar estado'), ('PERMISSION_CHANGE', 'Cambiar permiso'), ('ROLE_CHANGE', 'Cambiar rol')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('record_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('prev_data', models.JSONField(blank=True, null=True)),
                ('post_data', models.JSONField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('result', models.CharField(db_index=True, default='SUCCESS', max_length=50)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'record_id', '-timestamp'], name='audit_audit_entity__3b1067_idx')],
            },
        ),
    ]
