# Generated by Django 5.2.16 on 2026-07-14 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de archivado')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=100, verbose_name='Tipo de inmueble')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('stratum', models.IntegerField(verbose_name='Estrato')),
                ('area', models.FloatField(verbose_name='Área (m²)')),
                ('rent_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor canon')),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Porcentaje admin')),
                ('status', models.CharField(default='Disponible', max_length=50, verbose_name='Estado')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owners.owner', verbose_name='Propietario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
