# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('configuration', '0001_initial'),
        ('owners', '0001_initial'),
        ('properties', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinventory',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='propertyinventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='properties.propertyinventory'),
        ),
        migrations.AddField(
            model_name='propertylevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertylevel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertylevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(related_name='properties', through='properties.PropertyOwnership', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_accounts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_accounts', to='catalogs.utilityprovider'),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyutilityaccount',
            name='utility_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_accounts', to='catalogs.utilitytype'),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='administration_fee_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_listings', to='configuration.administrationfeeplan'),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_listings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='rentallisting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilityevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilityevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilityevent',
            name='utility_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='properties.propertyutilityaccount'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('concept__isnull', False), models.Q(('custom_name', ''), _negated=True), _connector='OR'), name='ck_inventory_item_name'),
        ),
        migrations.AddConstraint(
            model_name='propertylevel',
            constraint=models.CheckConstraint(condition=models.Q(('level_to__isnull', True), ('level_to__gte', models.F('level_from')), _connector='OR'), name='ck_property_level_range'),
        ),
        migrations.AddConstraint(
            model_name='propertyownership',
            constraint=models.UniqueConstraint(fields=('property', 'owner', 'valid_from'), name='uq_property_owner_period'),
        ),
        migrations.AddConstraint(
            model_name='propertyownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('valid_to__isnull', True)), fields=('property',), name='uq_property_primary_owner'),
        ),
        migrations.AddConstraint(
            model_name='propertyownership',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ck_ownership_valid_dates'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='properties__city_id_1f2cde_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'operational_status'], name='properties__propert_e0acef_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyutilityaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'contract_number'), name='uq_utility_contract_provider'),
        ),
        migrations.AddConstraint(
            model_name='rentallisting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'AVAILABLE', 'PAUSED'])), fields=('property',), name='uq_property_open_rental_listing'),
        ),
    ]
