# Generated by Django 5.2.16 on 2026-07-14 05:08

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('owners', '0001_initial'),
        ('properties', '0001_initial'),
        ('repairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre visible')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Archivo')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiqueta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME Type')),
                ('extension', models.CharField(max_length=20, verbose_name='Extensión')),
                ('size', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('checksum', models.CharField(max_length=64, verbose_name='Checksum SHA-256')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivado')),
                ('entity_type', models.CharField(default='general', max_length=100, verbose_name='Tipo de entidad asociada')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.documenttype', verbose_name='Tipo de documento')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='owners.owner')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='repairs.repair')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
