# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('required_permission', models.CharField(max_length=150)),
                ('available_formats', models.JSONField(default=list)),
                ('filter_schema', models.JSONField(default=dict)),
                ('column_schema', models.JSONField(default=list)),
                ('default_order', models.JSONField(default=list)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filters', models.JSONField(default=dict)),
                ('output_format', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Generando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('EXPIRED', 'Expirado')], db_index=True, default='PENDING', max_length=10)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reports.reportdefinition')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='INFO', max_length=10)),
                ('object_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta'), ('DISMISSED', 'Descartada')], db_index=True, default='OPEN', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKNOWLEDGED'])), fields=('alert_type', 'content_type', 'object_id'), name='uq_open_alert_entity_type')],
            },
        ),
    ]
