# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('configuration', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0001_initial'),
        ('owners', '0001_initial'),
        ('payments', '0001_initial'),
        ('people', '0001_initial'),
        ('properties', '0002_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingperiod',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charge',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charge',
            name='billing_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.billingperiod'),
        ),
        migrations.AddField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charge',
            name='financial_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='catalogs.financialconcept'),
        ),
        migrations.AddField(
            model_name='charge',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='people.party'),
        ),
        migrations.AddField(
            model_name='charge',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='charge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_charge_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payments.charge'),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='support_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document'),
        ),
        migrations.AddField(
            model_name='chargeadjustment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_fee_assessments', to='payments.charge'),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='configuration.latefeepolicy'),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='payment_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owners.ownerpaymentinstruction'),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.paymentmethod'),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='support_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document'),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundaccount',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fund_account', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='ownerfundaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='payments.ownerfundaccount'),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='financial_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.financialconcept'),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_owner_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='owners.owner'),
        ),
        migrations.AddField(
            model_name='ownersettlement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerdisbursement',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='payments.ownersettlement'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='financial_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.financialconcept'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='properties.property'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payments.ownersettlement'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ownersettlementline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='people.party'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='catalogs.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='payments.charge'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='configuration.office'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='configuration.organization'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='people.party'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='related_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related', to='payments.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownerfundmovement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_movements', to='payments.receipt'),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_payments', to='payments.receipt'),
        ),
        migrations.AddField(
            model_name='receiptpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptversion',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='payments.receipt'),
        ),
        migrations.AddField(
            model_name='receiptversion',
            name='rendered_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.document'),
        ),
        migrations.AddField(
            model_name='receiptversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_receipts', to='payments.receiptversion'),
        ),
        migrations.AddField(
            model_name='receiptversionline',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.financialconcept'),
        ),
        migrations.AddField(
            model_name='receiptversionline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptversionline',
            name='receipt_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payments.receiptversion'),
        ),
        migrations.AddField(
            model_name='receiptversionline',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='receiptversionline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'period_start', 'period_end'), name='uq_accounting_period'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='ck_period_dates'),
        ),
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['status', 'due_date'], name='payments_bi_status_da7274_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('rental', 'period_start', 'period_end'), name='uq_rental_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='ck_billing_dates'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['party', 'status', 'due_date'], name='payments_ch_party_i_29938c_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_amount__lte', models.F('original_amount'))), name='ck_charge_balance'),
        ),
        migrations.AddConstraint(
            model_name='ownersettlement',
            constraint=models.UniqueConstraint(fields=('owner', 'period_start', 'period_end'), name='uq_owner_settlement_period'),
        ),
        migrations.AddConstraint(
            model_name='ownersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='ck_settlement_dates'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uq_payment_charge_allocation'),
        ),
        migrations.AddConstraint(
            model_name='receiptpayment',
            constraint=models.UniqueConstraint(fields=('receipt', 'payment'), name='uq_receipt_payment'),
        ),
        migrations.AddConstraint(
            model_name='receiptversion',
            constraint=models.UniqueConstraint(fields=('receipt', 'version_number'), name='uq_receipt_version_number'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_type', 'number'), name='uq_receipt_number'),
        ),
    ]
