# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('party_type', models.CharField(choices=[('NATURAL', 'Persona natural'), ('LEGAL', 'Persona jurídica')], max_length=10)),
                ('identification_number', models.CharField(max_length=50)),
                ('verification_digit', models.CharField(blank=True, max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='catalogs.identificationtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona o empresa',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('HOME', 'Residencia'), ('WORK', 'Trabajo'), ('PAYMENT', 'Entrega de pagos'), ('OTHER', 'Otra')], max_length=10)),
                ('address_line', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.department')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.neighborhood')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='people.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('allows_notifications', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='people.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyIdentification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issue_place', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.identificationtype')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifications', to='people.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_type', models.CharField(choices=[('MOBILE', 'Celular'), ('HOME', 'Residencia'), ('WORK', 'Trabajo'), ('OTHER', 'Otro')], max_length=10)),
                ('country_code', models.CharField(default='+57', max_length=5)),
                ('number', models.CharField(max_length=30)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('allows_notifications', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='people.party')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('legacy_source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('provider_kind', models.CharField(choices=[('CONTRACTOR', 'Maestro o contratista'), ('COMPANY', 'Empresa'), ('HARDWARE_STORE', 'Ferretería'), ('OTHER', 'Otro')], max_length=20)),
                ('tax_responsibility', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_profile', to='people.party')),
                ('specialties', models.ManyToManyField(blank=True, related_name='providers', to='catalogs.providerspecialty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['display_name'], name='people_part_display_e25529_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['identification_number'], name='people_part_identif_ad78e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('identification_type', 'identification_number'), name='uq_party_identification'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('first_name__gt', ''), ('party_type', 'NATURAL')), models.Q(('business_name__gt', ''), ('party_type', 'LEGAL')), _connector='OR'), name='ck_party_name_for_type'),
        ),
        migrations.AddConstraint(
            model_name='partyaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party',), name='uq_party_primary_address'),
        ),
        migrations.AddConstraint(
            model_name='partyemail',
            constraint=models.UniqueConstraint(fields=('party', 'email'), name='uq_party_email'),
        ),
        migrations.AddConstraint(
            model_name='partyemail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party',), name='uq_party_primary_email'),
        ),
        migrations.AddConstraint(
            model_name='partyidentification',
            constraint=models.UniqueConstraint(fields=('identification_type', 'number'), name='uq_party_extra_identification'),
        ),
        migrations.AddConstraint(
            model_name='partyidentification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party',), name='uq_party_one_primary_identification'),
        ),
        migrations.AddConstraint(
            model_name='partyphone',
            constraint=models.UniqueConstraint(fields=('party', 'country_code', 'number'), name='uq_party_phone'),
        ),
        migrations.AddConstraint(
            model_name='partyphone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('party',), name='uq_party_primary_phone'),
        ),
    ]
