# Generated by Django 5.2.16 on 2026-07-15 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guarantors', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalguarantee',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rentalguarantee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guaranteecase',
            name='rental_guarantee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='guarantors.rentalguarantee'),
        ),
        migrations.AddConstraint(
            model_name='rentalguarantee',
            constraint=models.UniqueConstraint(fields=('guarantor_company', 'policy_number'), name='uq_guarantee_policy_number'),
        ),
        migrations.AddConstraint(
            model_name='rentalguarantee',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end__gte', models.F('coverage_start'))), name='ck_guarantee_dates'),
        ),
    ]
